export const GET_ALL_PRODUCTS_LIST_REQUEST = 'GET_ALL_PRODUCTS_LIST_REQUEST';
export const GET_ALL_PRODUCTS_LIST_SUCCESS = 'GET_ALL_PRODUCTS_LIST_SUCCESS';
export const GET_ALL_PRODUCTS_LIST_FAILURE = 'GET_ALL_PRODUCTS_LIST_FAILURE';

export const GET_MENS_CLOTHING_REQUEST = 'GET_MENS_CLOTHING_REQUEST';
export const GET_MENS_CLOTHING_SUCCESS = 'GET_MENS_CLOTHING_SUCCESS';
export const GET_MENS_CLOTHING_FAILURE = 'GET_MENS_CLOTHING_FAILURE';

export const GET_WOMENS_CLOTHING_REQUEST = 'GET_WOMENS_CLOTHING_REQUEST';
export const GET_WOMENS_CLOTHING_SUCCESS = 'GET_WOMENS_CLOTHING_SUCCESS';
export const GET_WOMENS_CLOTHING_FAILURE = 'GET_WOMENS_CLOTHING_FAILURE';

export const GET_ELECTRONICS_REQUEST = 'GET_ELECTRONICS_REQUEST';
export const GET_ELECTRONICS_SUCCESS = 'GET_ELECTRONICS_SUCCESS';
export const GET_ELECTRONICS_FAILURE = 'GET_ELECTRONICS_FAILURE';

export const GET_JEWELERY_ITEMS_REQUEST = 'GET_JEWELERY_ITEMS_REQUEST';
export const GET_JEWELERY_ITEMS_SUCCESS = 'GET_JEWELERY_ITEMS_SUCCESS';
export const GET_JEWELERY_ITEMS_FAILURE = 'GET_JEWELERY_ITEMS_FAILURE';
