
 export const GET_MENS_PRODUCTS = "GET_MENS_PRODUCTS";
 export const GET_MENS_PRODUCTS_SUCCESS="GET_MENS_PRODUCTS_SUCCESS";
 export const GET_MENS_PRODUCTS_FAILED="GET_MENS_PRODUCTS_FAILED";
 export const SELECTED_PRODUCT= "SELECTED_PRODUCT";
 export const REMOVE_SELECTED_PRODUCT ="REMOVE_SELECTED_PRODUCT";
