export const GET_JEWELERY_PRODUCTS = "GET_JEWELERY_PRODUCTS";
export const GET_JEWELERY_PRODUCTS_SUCCESS="GET_JEWELERY_PRODUCTS_SUCCESS";
export const GET_JEWELERY_PRODUCTS_FAILED="GET_JEWELERY_PRODUCTS_FAILED";